### ISSUE TITLE
Good Start

### ISSUE THREAD

**Issue by arvindstutzen** [kirmorozov/magento-gae#1]
Like the approach and idea. But do you think it is possible overall to make it working ? And do we have roadmap and plan for it ?

**Comment by kirmorozov** [comment]
It worked when google provided free micro mysql instance.
Main trouble was with file_exists check in google storage for caching images.
I was excited when I started it, but It looks inefficient cost/CPU usage with GAE.

Page rendering was about 2 seconds. 
If you want to continue development/try, I can share access to GAE account.

**Comment by arvindstutzen** [comment]
Ok so its no way magneto can work in appengine in near future on current
techstack . thanks for ground work

**Comment by kirmorozov** [comment]
Welcome to the future :)
